import { ColumnConfig } from "../columnconfig";

// Define the inventory columns with their configurations

export const inventoryCols: ColumnConfig[] = [
//   new ColumnConfig('id', 'Id', true, '#EDEDEE', '#000'),
//   new ColumnConfig('rawdataId', 'RawdataId', true, '#EDEDEE', '#000'),
  new ColumnConfig('materialID', 'MaterialID', true, '#EDEDEE', '#000'),
  new ColumnConfig('generalAccount', 'General Account', true, '#EDEDEE', '#000', 200),
  new ColumnConfig('jackAndStMalo', 'Jack St. Malo', true, '#EDEDEE', '#000', 200),
  new ColumnConfig('tahiti', 'Tahiti', true, '#EDEDEE', '#000'),
  new ColumnConfig('bigFoot', 'Big Foot', true, '#EDEDEE', '#000'),
  new ColumnConfig('blindFaith', 'Blind Faith', true, '#EDEDEE', '#000'),
  new ColumnConfig('anchor', 'Anchor', true, '#EDEDEE', '#000'),
  new ColumnConfig('ballymore', 'Ballymore', true, '#EDEDEE', '#000'),
  new ColumnConfig('surplus', 'Surplus', true, '#EDEDEE', '#000'),
  new ColumnConfig('category2Bucket', 'Category2Bucket', true, '#EDEDEE', '#000', 210),
  new ColumnConfig('plantCode', 'PlantCode', true, '#EDEDEE', '#000'),
  new ColumnConfig('partnerAuditClaimPlantCode', 'Partner Audit Claim Plant Code', true, '#EDEDEE', '#000', 300),
  new ColumnConfig('asset', 'Asset', true, '#EDEDEE', '#000'),
  new ColumnConfig('onHandQuantity', 'OnHandQuantity', true, '#EDEDEE', '#000', 200),
  new ColumnConfig('valuationType', 'ValuationType', true, '#EDEDEE', '#000', 200),
  new ColumnConfig('inventoryItemID', 'InventoryItemID', true, '#EDEDEE', '#000',200),
  new ColumnConfig('oldInventoryItemID', 'OldInventoryItemID', true, '#EDEDEE', '#000', 220),
  new ColumnConfig('sourceSystem', 'SourceSystem', true, '#EDEDEE', '#000', 200),
  new ColumnConfig('originalSourceSystem', 'OriginalSourceSystem', true, '#EDEDEE', '#000' , 220),
  new ColumnConfig('businessUnitID', 'BusinessUnitID', true, '#EDEDEE', '#000', 200),
  new ColumnConfig('plantName', 'PlantName', true, '#EDEDEE', '#000'),
  new ColumnConfig('storageLocationDesc', 'StorageLocationDesc', true, '#EDEDEE', '#000', 230),
  new ColumnConfig('storageLocationCode', 'StorageLocationCode', true, '#EDEDEE', '#000', 230),
  new ColumnConfig('storageBin', 'StorageBin', true, '#EDEDEE', '#000'),
  new ColumnConfig('batch', 'Batch', true, '#EDEDEE', '#000'),
  new ColumnConfig('wbsElementID', 'WBSElementID', true, '#EDEDEE', '#000', 200),
  new ColumnConfig('wbsElementDesc', 'WBSElementDesc', true, '#EDEDEE', '#000', 210),
  new ColumnConfig('category1Asset', 'Category1Asset', true, '#EDEDEE', '#000', 200),
  new ColumnConfig('serialNumber', 'SerialNumber', true, '#EDEDEE', '#000', 200),
  new ColumnConfig('oldMaterialNumber', 'OldMaterialNumber', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('materialType', 'MaterialType', true, '#EDEDEE', '#000',180),
  new ColumnConfig('materialShortDesc', 'MaterialShortDesc', true, '#EDEDEE', '#000', 250),
  new ColumnConfig('materialLongDesc', 'MaterialLongDesc', true, '#EDEDEE', '#000', 230),
  new ColumnConfig('manufacturingPartNumber', 'ManufacturingPartNumber', true, '#EDEDEE', '#000' , 250),
  new ColumnConfig('tier', 'Tier', true, '#EDEDEE', '#000'),
  new ColumnConfig('od', 'OD', true, '#EDEDEE', '#000'),
  new ColumnConfig('wallThickness', 'WallThickness', true, '#EDEDEE', '#000' , 200),
  new ColumnConfig('weight', 'Weight', true, '#EDEDEE', '#000'),
  new ColumnConfig('grade', 'Grade', true, '#EDEDEE', '#000'),
  new ColumnConfig('connection', 'Connection', true, '#EDEDEE', '#000'),
  new ColumnConfig('sourService', 'SourService', true, '#EDEDEE', '#000'),
  new ColumnConfig('uoM', 'UoM', true, '#EDEDEE', '#000'),
  new ColumnConfig('aUoM', 'AUoM', true, '#EDEDEE', '#000'),
  new ColumnConfig('materialCondition', 'MaterialCondition', true, '#EDEDEE', '#000' , 200),
  new ColumnConfig('enterpriseCategory', 'EnterpriseCategory', true, '#EDEDEE', '#000',  200),
  new ColumnConfig('segment', 'Segment', true, '#EDEDEE', '#000'),
  new ColumnConfig('family', 'Family', true, '#EDEDEE', '#000'),
  new ColumnConfig('class', 'Class', true, '#EDEDEE', '#000'),
  new ColumnConfig('mRPType', 'MRPType', true, '#EDEDEE', '#000'),
  new ColumnConfig('mRPArea', 'MRPArea', true, '#EDEDEE', '#000'),
  new ColumnConfig('mRPTypeAtMRPArea', 'MRPTypeAtMRPArea', true, '#EDEDEE', '#000' , 200),
  new ColumnConfig('mRPTypeAtPlant', 'MRPTypeAtPlant', true, '#EDEDEE', '#000' , 200),
  new ColumnConfig('purchaseGroup', 'PurchaseGroup', true, '#EDEDEE', '#000' , 200),
  new ColumnConfig('externalMaterialGroup', 'ExternalMaterialGroup', true, '#EDEDEE', '#000' , 220),
  new ColumnConfig('materialGroup', 'MaterialGroup', true, '#EDEDEE', '#000' , 200),
  new ColumnConfig('criticalCode', 'CriticalCode', true, '#EDEDEE', '#000'),
  new ColumnConfig('criticalFlag', 'CriticalFlag', true, '#EDEDEE', '#000'),
  new ColumnConfig('critical', 'Critical', true, '#EDEDEE', '#000'),
  new ColumnConfig('materialStatus', 'MaterialStatus', true, '#EDEDEE', '#000' , 200),
  new ColumnConfig('specialStockType', 'SpecialStockType', true, '#EDEDEE', '#000' , 200),
  new ColumnConfig('jointVenture', 'JointVenture', true, '#EDEDEE', '#000',200),
  new ColumnConfig('maxQuantity', 'MaxQuantity', true, '#EDEDEE', '#000',200),
  new ColumnConfig('minQuantity', 'MinQuantity', true, '#EDEDEE', '#000',200),
  new ColumnConfig('blockQuantity', 'BlockQuantity', true, '#EDEDEE', '#000',200),
  new ColumnConfig('aUoMQuantity', 'AUoMQuantity', true, '#EDEDEE', '#000',200),
  new ColumnConfig('totalQuantity', 'TotalQuantity', true, '#EDEDEE', '#000',200),
  new ColumnConfig('unitPriceLocal', 'UnitPriceLocal', true, '#EDEDEE', '#000',200),
  new ColumnConfig('unitPriceUSD', 'UnitPriceUSD', true, '#EDEDEE', '#000', 210),
  new ColumnConfig('amountLocal', 'AmountLocal', true, '#EDEDEE', '#000',200),
  new ColumnConfig('amountUSD', 'AmountUSD', true, '#EDEDEE', '#000',200),
  new ColumnConfig('valuatedAmountUSD', 'ValuatedAmountUSD', true, '#EDEDEE', '#000' , 250),
  new ColumnConfig('valuatedAmountLocal', 'ValuatedAmountLocal', true, '#EDEDEE', '#000' , 250),
  new ColumnConfig('netBookValue', 'NetBookValue', true, '#EDEDEE', '#000',200),
  new ColumnConfig('openPOQuantity', 'OpenPOQuantity', true, '#EDEDEE', '#000',200),
  new ColumnConfig('openPOValue', 'OpenPOValue', true, '#EDEDEE', '#000',200),
  new ColumnConfig('leadTime', 'LeadTime', true, '#EDEDEE', '#000'),
  new ColumnConfig('forecastQuantity', 'ForecastQuantity', true, '#EDEDEE', '#000',200),
  new ColumnConfig('nonMovingLastIssueDate', 'NonMovingLastIssueDate', true, '#EDEDEE', '#000' , 250),
  new ColumnConfig('ageingCalculationDate', 'AgeingCalculationDate', true, '#EDEDEE', '#000' , 250),
  new ColumnConfig('lastUsedDateByBU', 'LastUsedDateByBU', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('lastUsedDateByPlant', 'LastUsedDateByPlant', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('lastMovementDateByPlant', 'LastMovementDateByPlant', true, '#EDEDEE', '#000' , 250),
  new ColumnConfig('assemblyID', 'AssemblyID', true, '#EDEDEE', '#000'),
  new ColumnConfig('itemType', 'ItemType', true, '#EDEDEE', '#000'),
  new ColumnConfig('supplier', 'Supplier', true, '#EDEDEE', '#000'),
  new ColumnConfig('supplierPartNumber', 'SupplierPartNumber', true, '#EDEDEE', '#000' , 250),
  new ColumnConfig('vendor', 'Vendor', true, '#EDEDEE', '#000'),
  new ColumnConfig('expectedDate', 'ExpectedDate', true, '#EDEDEE', '#000',200),
  new ColumnConfig('manufacturer', 'Manufacturer', true, '#EDEDEE', '#000'),
  new ColumnConfig('manufacturerDate', 'ManufacturerDate', true, '#EDEDEE', '#000',200),
  new ColumnConfig('size', 'Size', true, '#EDEDEE', '#000'),
  new ColumnConfig('length', 'Length', true, '#EDEDEE', '#000'),
  new ColumnConfig('documentNumber', 'DocumentNumber', true, '#EDEDEE', '#000',200),
  new ColumnConfig('documentLineNumber', 'DocumentLineNumber', true, '#EDEDEE', '#000',200),
  new ColumnConfig('commodityCode', 'CommodityCode', true, '#EDEDEE', '#000',200),
  new ColumnConfig('commodityCodeDesc', 'CommodityCodeDesc', true, '#EDEDEE', '#000',250),
  new ColumnConfig('demandFlag', 'DemandFlag', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('moveQuantity', 'MoveQuantity', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('costCenterID', 'CostCenterID', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('costCenterName', 'CostCenterName', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('surplusFlag', 'SurplusFlag', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('hashDiff', 'HashDiff', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('deleted', 'Deleted', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('createdTS', 'CreatedTS', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('lastUpdatedTS', 'LastUpdatedTS', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('transferOpportunityFlag', 'TransferOpportunityFlag', true, '#EDEDEE', '#000' ,230),
  new ColumnConfig('derivedLastMovementDate', 'DerivedLastMovementDate', true, '#EDEDEE', '#000' ,230),
  new ColumnConfig('ageTimeBucket', 'AgeTimeBucket', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('ageByMovementInMonths', 'AgeByMovementInMonths', true, '#EDEDEE', '#000',200),
  new ColumnConfig('materialAgeInMonths', 'MaterialAgeInMonths', true, '#EDEDEE', '#000',200),
  new ColumnConfig('lastUsedByBUInMonths', 'LastUsedByBUInMonths', true, '#EDEDEE', '#000',200),
  new ColumnConfig('proposedStatus', 'ProposedStatus', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('proposedReason', 'ProposedReason', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('investmentRecoveryStatus', 'InvestmentRecoveryStatus', true, '#EDEDEE', '#000' ,230),
  new ColumnConfig('orgFunction', 'OrgFunction', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('ageTimeBucketSort', 'AgeTimeBucketSort', true, '#EDEDEE', '#000' ,200),
  new ColumnConfig('crateID', 'CrateID', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('crateName', 'CrateName', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('tagId', 'TagId', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('ageingDate', 'AgeingDate', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('lastUsedDate', 'LastUsedDate', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('ageingMovementType', 'AgeingMovementType', true, '#EDEDEE', '#000',200),
  new ColumnConfig('lastUsedMovementType', 'LastUsedMovementType', true, '#EDEDEE', '#000',200),
  new ColumnConfig('ageingTimeFrame', 'AgeingTimeFrame', true, '#EDEDEE', '#000',200),
  new ColumnConfig('lastUsedTimeFrame', 'LastUsedTimeFrame', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('lastMovementTimeFrame', 'LastMovementTimeFrame', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('valuationClass', 'ValuationClass', true, '#EDEDEE', '#000', 210),
  new ColumnConfig('mMRLevel1Category', 'MMRLevel1Category', true, '#EDEDEE', '#000' ,250),
  new ColumnConfig('mMRLevel2Category', 'MMRLevel2Category', true, '#EDEDEE', '#000' ,250),
  new ColumnConfig('mMRLevel3Category', 'MMRLevel3Category', true, '#EDEDEE', '#000' ,250),
  new ColumnConfig('chevronMMR', 'ChevronMMR', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('connectionConfiguration', 'ConnectionConfiguration', true, '#EDEDEE', '#000' ,250),
  new ColumnConfig('qualityPlan', 'QualityPlan', true, '#EDEDEE', '#000' , 230),
  new ColumnConfig('readyForServiceDate', 'ReadyForServiceDate', true, '#EDEDEE', '#000',230),
//   new ColumnConfig('dateCreated', 'DateCreated', true, '#EDEDEE', '#000'),
//   new ColumnConfig('userIdCreatedBy', 'UserIdCreatedBy', true, '#EDEDEE', '#000'),
//   new ColumnConfig('dateLastModified', 'DateLastModified', true, '#EDEDEE', '#000'),
//   new ColumnConfig('userIdModifiedBy', 'UserIdModifiedBy', true, '#EDEDEE', '#000'),
//   new ColumnConfig('isDeleted', 'IsDeleted', true, '#EDEDEE', '#000'),
];