import { Injectable } from "@angular/core";

@Injectable({
  providedIn: 'root',
})

export class ExcelColumnMapService
{
    // raw data key map
    rawDataKeyMap: Record<string, string> = {
        'Material Id': 'MaterialId',
        'Description': 'Description',
        'Transaction Type': 'TransactionType',
        'Expected Delivery Date': 'ExpectedDeliveryDate',
        'Quantity': 'Quantity',
        'Add To Starting Inventory':'AddtoStartingInventory',
        'Well Number':'WellNumber',
        'Supplier':'Supplier',
        'Product Type':'ProductType',
        'Order Comments':'OrderComments',
        'Order Status':'OrderStatus',
        'Shipment Forecasted Quantity':'ShipmentForecastedQuantity',
        'Connection':'Connection',
        'Price Per Foot':'PricePerFoot',
        'OrderNumber':'OrderNumber',
      };
    // yard inventory key map
    yardInventoryKeyMap: Record<string, string> = {
        'Material Number': 'MaterialNumber',
        'Product Name': 'ProductName',
        'Lot/Serial Number': 'LotSerialNumber',
        'Location': 'Location',
        'Stocking Location': 'StockingLocation',
        'Length': 'Length',
        'Heat Number': 'HeatNumber',
        'Class': 'Class',
        'Condition': 'Condition',
        'Accessory': 'Accessory',
        'SO#': 'SONumber',
        'Well Name': 'WellName',
        'WBS': 'WBS',
        'Project': 'Project',
        'Plant Code': 'PlantCode',
        'SLOC Code': 'SLOCCode'
    };
   //schematic clamp/control line keymap
      clampandControlLinekeyMap: Record<string, string> = {
        'Manufacturer Part #': 'manufacturerPart',
        'Halliburton Part #': 'halliburtonPart',
        'Material Key': 'materialKey',
        'Material Number': 'materialNumber',
        'Min Quantity (Primary)': 'primaryDemand',
        'Total Quantity Provided': 'totalQty',
        'Contingency Demand': 'contingencyDemand',
        'Details': 'details',
        'Type': 'type',
        'Unit Cost':'unitCost',
        'As-Built Quantity':'asBuiltQuantity',
        'Consumption Value':'consumptionValue'
      };
// tenaris excel key map
      tenarisDataKeyMap: Record<string, string> = {
        'MM #': 'MaterialId',
        'Description' :'Description',
        'Transaction Type': 'TransactionType',
        'Quantity': 'Quantity',
        'Estimated Delivery Date': 'ExpectedDeliveryDate',
        'Unit Price (USD)':'unitPrice'
       
      };

      // Vallorec excel key map
      vallorecDataKeyMap: Record<string, string> = {
        'Product Type':'ProductType',
        'Chevron SAP Material Master Number (MM#)': 'MaterialId',
        'Long Description': 'LongDescription',
        'Order Quantity (FT)':'OrderQty',
        'Order Comments (Current Report)':'OrderComments',
        'ORDER STATUS':'OrderStatus',
        'Shipment Forecasted Quantity (ft)':'ShipmentForeCastQty',
        'Expected Delivery Date': 'ExpectedDeliveryDate',  // order changes
        'Price Per Foot':'PricePerFoot'
        };

      // miti column mapping
    MitiDataKeyMap: Record<string, string> = {
      'Contract': 'Contract',
      'Miti So No': 'MitiSoNo',
      'Description': 'Description',
      'CVX Po': 'CVXPo',
      'Project': 'Project',
      'CVX Engineer': 'CVXEngineer',
      'Well': 'Well',
      'WBS': 'WBS',
      'CVX MM': 'CVXMM',
      'Sooner SN No': 'SoonerSNNo',
      'Line Number': 'LineNumber',
      'Comm': 'Comm',
      'Grade': 'Grade',
      'ODIN': 'ODIN',
      'WTIN': 'WTIN',
      'WTLbsPerFt': 'WTLbsPerFt',
      'LengthFt': 'LengthFt',
      'End': 'End',
      'Quantity Ft': 'QuantityFt',
      'Quantity Pc':'QuantityPc',
      'CVX Required Delivery Month Year': 'CVXRequiredDeliveryMonthYear',
      'Partial': 'Partial',
      'Vessel': 'Vessel',
      'ETD': 'ETD',
      'ETA': 'ETA',
      'Delivery Date': 'DeliveryDate',
      'Receiving Report': 'ReceivingReport',
      'Status': 'Status',
      'SOPriceMatOnly': 'SOPriceMatOnly',
      'Suppplier':'Suppplier'
  }

     // liner hanger excel key map
      lhAndWellHeadDataKeyMap: Record<string, string> = {
       
        'Material Type': 'MaterialType',
        'Supplier': 'Supplier',
        'Chevron MM #':'MaterialNumber',
        'Description':'Description',
        'Plant Code':'PlantCode',
        'Supplier Part #':'SupplierPartNumber',
        'PO #':'PONumber',
        'Heat #':'HeatNumber',
        'Order Date': 'OrderDate',
        'WBS': 'WBS',
        'Project':'Project',
        'Unit Cost':'UnitCost',
        'Quantity':'Quantity',
        'Estimated Delivery Date':'EstimatedDeliveryDate',
        'New Order Lead Times (Days)':'NewOrderLeadTimeDays',
        'Comments':'Comments'

      };

      // inventory excel key map
      inventoryDataKeyMap: Record<string,string>={
          'ID': 'ID',
          'InventoryItemID': 'InventoryItemID',
          'OldInventoryItemID': 'OldInventoryItemID',
          'SourceSystem': 'SourceSystem',
          'OriginalSourceSystem': 'OriginalSourceSystem',
          'BusinessUnitID': 'BusinessUnitID',
          'PlantCode': 'PlantCode',
          'PlantName': 'PlantName',
          'StorageLocationDesc': 'StorageLocationDesc',
          'StorageLocationCode': 'StorageLocationCode',
          'StorageBin': 'StorageBin',
          'Batch': 'Batch',
          'WbsElementID': 'WbsElementID',
          'WbsElementDesc': 'WbsElementDesc',
          'Asset': 'Asset',
          'Category2Bucket': 'Category2Bucket',
          'Category1Asset': 'Category1Asset',
          'MaterialID': 'MaterialID',
          'SerialNumber': 'SerialNumber',
          'OldMaterialNumber': 'OldMaterialNumber',
          'MaterialType': 'MaterialType',
          'MaterialShortDesc': 'MaterialShortDesc',
          'MaterialLongDesc': 'MaterialLongDesc',
          'ManufacturingPartNumber': 'ManufacturingPartNumber',
          'Tier': 'Tier',
          'OD': 'OD',
          'WallThickness': 'WallThickness',
          'Weight': 'Weight',
          'Grade': 'Grade',
          'Connection': 'Connection',
          'SourService': 'SourService',
          'UoM': 'UoM',
          'AUoM': 'AUoM',
          'MaterialCondition': 'MaterialCondition',
          'EnterpriseCategory': 'EnterpriseCategory',
          'Segment': 'Segment',
          'Family': 'Family',
          'Class': 'Class',
          'MRPType': 'MRPType',
          'MRPArea': 'MRPArea',
          'MRPTypeAtMRPArea': 'MRPTypeAtMRPArea',
          'MRPTypeAtPlant': 'MRPTypeAtPlant',
          'PurchaseGroup': 'PurchaseGroup',
          'ExternalMaterialGroup': 'ExternalMaterialGroup',
          'MaterialGroup': 'MaterialGroup',
          'CriticalCode': 'CriticalCode',
          'CriticalFlag': 'CriticalFlag',
          'Critical': 'Critical',
          'MaterialStatus': 'MaterialStatus',
          'ValuationType': 'ValuationType',
          'SpecialStockType': 'SpecialStockType',
          'JointVenture': 'JointVenture',
          'MaxQuantity': 'MaxQuantity',
          'MinQuantity': 'MinQuantity',
          'OnHandQuantity': 'OnHandQuantity',
          'BlockQuantity': 'BlockQuantity',
          'AUoMQuantity': 'AUoMQuantity',
          'TotalQuantity': 'TotalQuantity',
          'UnitPriceLocal': 'UnitPriceLocal',
          'UnitPriceUSD': 'UnitPriceUSD',
          'AmountLocal': 'AmountLocal',
          'AmountUSD': 'AmountUSD',
          'ValuatedAmountUSD': 'ValuatedAmountUSD',
          'ValuatedAmountLocal': 'ValuatedAmountLocal',
          'NetBookValue': 'NetBookValue',
          'OpenPOQuantity': 'OpenPOQuantity',
          'OpenPOValue': 'OpenPOValue',
          'LeadTime': 'LeadTime',
          'ForecastQuantity': 'ForecastQuantity',
          'NonMovingLastIssueDate': 'NonMovingLastIssueDate',
          'AgeingCalculationDate': 'AgeingCalculationDate',
          'LastUsedDateByBU': 'LastUsedDateByBU',
          'LastUsedDateByPlant': 'LastUsedDateByPlant',
          'LastMovementDateByPlant': 'LastMovementDateByPlant',
          'AssemblyID': 'AssemblyID',
          'ItemType': 'ItemType',
          'Supplier': 'Supplier',
          'SupplierPartNumber': 'SupplierPartNumber',
          'Vendor': 'Vendor',
          'ExpectedDate': 'ExpectedDate',
          'Manufacturer': 'Manufacturer',
          'ManufacturerDate': 'ManufacturerDate',
          'Size': 'Size',
          'Length': 'Length',
          'DocumentNumber': 'DocumentNumber',
          'DocumentLineNumber': 'DocumentLineNumber',
          'CommodityCode': 'CommodityCode',
          'CommodityCodeDesc': 'CommodityCodeDesc',
          'DemandFlag': 'DemandFlag',
          'MoveQuantity': 'MoveQuantity',
          'CostCenterID': 'CostCenterID',
          'CostCenterName': 'CostCenterName',
          'SurplusFlag': 'SurplusFlag',
          'HashDiff': 'HashDiff',
          'Deleted': 'Deleted',
          'CreatedTS': 'CreatedTS',
          'LastUpdatedTS': 'LastUpdatedTS',
          'TransferOpportunityFlag': 'TransferOpportunityFlag',
          'DerivedLastMovementDate': 'DerivedLastMovementDate',
          'AgeTimeBucket': 'AgeTimeBucket',
          'AgeByMovementInMonths': 'AgeByMovementInMonths',
          'MaterialAgeInMonths': 'MaterialAgeInMonths',
          'LastUsedByBUInMonths': 'LastUsedByBUInMonths',
          'ProposedStatus': 'ProposedStatus',
          'ProposedReason': 'ProposedReason',
          'InvestmentRecoveryStatus': 'InvestmentRecoveryStatus',
          'OrgFunction': 'OrgFunction',
          'AgeTimeBucketSort': 'AgeTimeBucketSort',
          'CrateID': 'CrateID',
          'CrateName': 'CrateName',
          'TagId': 'TagId',
          'AgeingDate': 'AgeingDate',
          'LastUsedDate': 'LastUsedDate',
          'AgeingMovementType': 'AgeingMovementType',
          'LastUsedMovementType': 'LastUsedMovementType',
          'AgeingTimeFrame': 'AgeingTimeFrame',
          'LastUsedTimeFrame': 'LastUsedTimeFrame',
          'LastMovementTimeFrame': 'LastMovementTimeFrame',
          'ValuationClass': 'ValuationClass',
          'MMRLevel1Category': 'MMRLevel1Category',
          'MMRLevel2Category': 'MMRLevel2Category',
          'MMRLevel3Category': 'MMRLevel3Category',
          'ChevronMMR': 'ChevronMMR',
          'ConnectionConfiguration': 'ConnectionConfiguration',
          'QualityPlan': 'QualityPlan',
          'ReadyForServiceDate': 'ReadyForServiceDate'
      };

      //wellhead key map
      wellHeadDataKeyMap: Record<string, string> = {
       
        'Due': 'Due',
        'Order Line': 'OrderLine',
        'PO Number':'PONumber',
        'MM #':'MaterialNumber',
        'CP Num':'CPNum',
        'Customer/District':'CustomerDistrict',
        'Order No':'OrderNo',
        'Item':'Item',
        'Description':'Description',
        'Qty Open':'QtyOpen',
        'Sales Value':'SalesValue',
        'Cost Value':'CostValue',
        'Net Avail':'NetAvail',
        'Current Net':'CurrentNet',
        'Order Date': 'OrderDate',
        'Coord': 'Coord',
        'Type of Work':'TypeofWork',
        'Ord Status':'OrdStatus',
        'MTR/Job':'MTRJob',
        'Job Status':'JobStatus',
        'Comment':'Comment',
        'Delivery':'Delivery'

      };

      mdlDrillingKeyMap: Record<string, string> = {
      "ODIN Sequence": "BuildPriorityNumber",
      "Component Type": "MaterialType",
      "Material Description": "MaterialShortDesc",
      "Material ID": "MaterialId",
      "Market Unit Price": "MarketUnitPrice",
      "Tier": "Tier",
      "Hole Section": "HoleSection",
      "Hole Section Type": "HSType",
      "Material Group": "MGroup",
      "Nominal/Max OD (IN)": "OD",
      "Wall Thickness (IN)": "Wall",
      "Weight (LB)": "Weight",
      "Material Grade": "Grade",
      "Connection": "Connection",
      "Manufacturer": "vendor",
      "Supplier Part #": "manufacturerNum",
      "Sour Service": "SourService",
      "Manufacturer Name": "ManufacturerName",
      "UoM (FT or EA)": "UoM",
      "Manufacturer SAP #": "VendorSAPNumber"
    };

    mdlCompletionsKeyMap: Record<string, string> = {
      "MM# / MMR#": "MaterialNumber",
      "Is this Supplier Specific? 0 = No 1 = Yes": "IsSupplierSpecificFlag",
      "Supplier": "SupplierId",
      "Component Type": "ComponentTypeId",
      "Material Grade": "MaterialGradeId1",
      "Material Grade - Secondary": "MaterialGradeId2",
      "Material Grade - Tertiary": "MaterialGradeId3",
      "Range": "RangeId",
      "Top Connection": "TopendConnectionId",
      "Middle Connection": "MiddleendConnectionId",
      "Bottom Connection": "BottomendConnectionId",
      "Connection Configuration": "ConnectionConfigId",
      "Description": "MaterialDescription",
      "Trade Name": "TradeName",
      "Supplier Part #": "SupplierPartNumber",
      "Legacy Ref #": "LegacyRefNumber",
      "Nominal/Max OD (IN)": "NominalOd1",
      "Nominal/Max OD (IN) - Secondary": "NominalOd2",
      "Nominal OD/Max (IN) - Tertiary": "NominalOd3",
      "Wall Thickness (IN)": "WallThickness",
      "Min Yield Strength (PSI)": "YeildStrength",
      "Drift": "Drift",
      "Weight (LB)": "Weight1",
      "Weight (LB) - Secondary": "Weight2",
      "Weight (LB) - Tertiary": "Weight3",
      "Actual OD (IN)": "ActualOd1",
      "Actual OD (IN) - Secondary": "ActualOd2",
      "Actual OD (IN) - Tertiary": "ActualOd3",
      "Max Temperature Rating (F)": "MaxTempRating",
      "Actual ID (IN)": "ActualId1",
      "Actual ID (IN) - Secondary": "ActualId2",
      "Actual ID (IN) - Tertiary": "ActualId3",
      "Quality Plan Designation": "QualityPlanDesignation",
      "Min Temperature Rating (F) - Elastomers": "ElastomersMinTempRating",
      "Max Temperature Rating (F) - Elastomers": "ElastomersMaxTempRating",
      "Elastomer Notes": "ElastomerNotes",
      "Standard Notes": "StandardNotes",
      "Max Pressure Rating (PSI)": "MaxPressureRating",
      "Differential Pressure Rating (PSI)": "DiffPressureRating",
      "Burst Pressure (PSI)": "BurstPressure",
      "Collapse Pressure (PSI)": "CollapsePressure",
      "Manufacturer": "ManufacturerId",
      "Threaded Connection? 0 = No 1 = Yes": "IsThreadedConnection",
      "Contains Elastomer Elements? 0 = No 1 = Yes": "IsContainsElastomerElements",
      "Connection Burst Pressure": "ConnectionBurstPressure",
      "Connection Collapse Pressure": "ConnectionCollapsePressure",
      "Connection Yield Strength": "ConnectionYeildStrength",
      "Makeup Loss": "MakeupLoss",
      "Elastomer Type": "elastomerTypeID",
      "Group": "groupName",
      "Project Tag": "projectTags",
      "Administrative Notes":"AdministrativeNotes",
      "Material Group": "MaterialGroup",
      "Axial Strength (PSI)": "AxialStrength",
      "Connection Type": "ConnectionType",
      "Vendor SAP #": "VendorSAPNumber",
      "Unit of Measure": "UoM",
    };

      //expected header for bulk upload

      tenarisHeaders =['MM #',
        'Description'	,
        'Transaction Type',
        'Quantity',
        'Estimated Delivery Date',
        'Unit Price (USD)'
       ]
      valloureHeaders =[
        'Product Type',
        'Chevron SAP Material Master  Number (MM#)'	,
        'Long Description',
        'Order Quantity (FT)',
        'Order Comments (Current Report)',
        'Order Status',
        'Shipment Forecasted Quantity (ft)',
        'Expected Delivery Date',
        'Price Per Foot',
      ]
      
      // Yard Inventory headers
      YardInventoryHeaders = [
        'Material Number',
        'Product Name',
        'Lot/Serial Number',
        'Location',
        'Stocking Location',
        'Length',
        'Heat Number',
        'Class',
        'Condition',
        'Accessory',
        'SO#',
        'Well Name',
        'WBS',
        'Project',
        'Plant Code',
        'SLOC Code'
      ]

       lhAndWellHeadHeader=[
       
        'Material Type',
        'Supplier',
        'Chevron MM #',	
        'Description',	
        'Plant Code',	
        'Supplier Part #',	
        'PO #',
        'Heat #',	
        'Order Date',	
        'WBS',
        'Project',	
        'Unit Cost',	
        'Quantity',	
        'Estimated Delivery Date',	
        'New Order Lead Times (Days)',	
        'Comments'
       ]
        wellHeadHeader=[
       
        'Due',
        'Order Line',
        'PO Number',
        'MM #',
        'CP Num',
        'Customer/District',
        'Order No',
        'Item',
        'Description',
        'Qty Open',
        'Sales Value',
        'Cost Value',
        'Net Avail',
        'Current Net',
        'Order Date',
        'Coord',
        'Type of Work',
        'Ord Status',
        'MTR/Job',
        'Job Status',
        'Comment',
        'Delivery'
       ]
       //inventory headers
       
       inventoryHeader = [
            'ID',
            'InventoryItemID',
            'OldInventoryItemID',
            'SourceSystem',
            'OriginalSourceSystem',
            'BusinessUnitID',
            'PlantCode',
            'PlantName',
            'StorageLocationDesc',
            'StorageLocationCode',
            'StorageBin',
            'Batch',
            'WbsElementID',
            'WbsElementDesc',
            'Asset',
            'Category2Bucket',
            'Category1Asset',
            'MaterialID',
            'SerialNumber',
            'OldMaterialNumber',
            'MaterialType',
            'MaterialShortDesc',
            'MaterialLongDesc',
            'ManufacturingPartNumber',
            'Tier',
            'OD',
            'WallThickness',
            'Weight',
            'Grade',
            'Connection',
            'SourService',
            'UoM',
            'AUoM',
            'MaterialCondition',
            'EnterpriseCategory',
            'Segment',
            'Family',
            'Class',
            'MRPType',
            'MRPArea',
            'MRPTypeAtMRPArea',
            'MRPTypeAtPlant',
            'PurchaseGroup',
            'ExternalMaterialGroup',
            'MaterialGroup',
            'CriticalCode',
            'CriticalFlag',
            'Critical',
            'MaterialStatus',
            'ValuationType',
            'SpecialStockType',
            'JointVenture',
            'MaxQuantity',
            'MinQuantity',
            'OnHandQuantity',
            'BlockQuantity',
            'AUoMQuantity',
            'TotalQuantity',
            'UnitPriceLocal',
            'UnitPriceUSD',
            'AmountLocal',
            'AmountUSD',
            'ValuatedAmountUSD',
            'ValuatedAmountLocal',
            'NetBookValue',
            'OpenPOQuantity',
            'OpenPOValue',
            'LeadTime',
            'ForecastQuantity',
            'NonMovingLastIssueDate',
            'AgeingCalculationDate',
            'LastUsedDateByBU',
            'LastUsedDateByPlant',
            'LastMovementDateByPlant',
            'AssemblyID',
            'ItemType',
            'Supplier',
            'SupplierPartNumber',
            'Vendor',
            'ExpectedDate',
            'Manufacturer',
            'ManufacturerDate',
            'Size',
            'Length',
            'DocumentNumber',
            'DocumentLineNumber',
            'CommodityCode',
            'CommodityCodeDesc',
            'DemandFlag',
            'MoveQuantity',
            'CostCenterID',
            'CostCenterName',
            'SurplusFlag',
            'HashDiff',
            'Deleted',
            'CreatedTS',
            'LastUpdatedTS',
            'TransferOpportunityFlag',
            'DerivedLastMovementDate',
            'AgeTimeBucket',
            'AgeByMovementInMonths',
            'MaterialAgeInMonths',
            'LastUsedByBUInMonths',
            'ProposedStatus',
            'ProposedReason',
            'InvestmentRecoveryStatus',
            'OrgFunction',
            'AgeTimeBucketSort',
            'CrateID',
            'CrateName',
            'TagId',
            'AgeingDate',
            'LastUsedDate',
            'AgeingMovementType',
            'LastUsedMovementType',
            'AgeingTimeFrame',
            'LastUsedTimeFrame',
            'LastMovementTimeFrame',
            'ValuationClass',
            'MMRLevel1Category',
            'MMRLevel2Category',
            'MMRLevel3Category',
            'ChevronMMR',
            'ConnectionConfiguration',
            'QualityPlan',
            'ReadyForServiceDate'
       ];

       //Miti headers
      mitiHeaders = [
        'Contract',
        'Miti So No',
        'Description',
        'CVX Po',
        'Project',
        'CVX Engineer',
        'Well',
        'WBS',
        'CVX MM',
        'Sooner SN No',
        'Line Number',
        'Comm',
        'Grade',
        'ODIN',
        'WTIN',
        'WTLbsPerFt',
        'LengthFt',
        'End',
        'Quantity Ft',
        'Quantity Pc',
        'CVX Required Delivery Month Year',
        'Partial',
        'Vessel',
        'ETD',
        'ETA',
        'Delivery Date',
        'Receiving Report',
        'Status',
        'SOPriceMatOnly',
        'Supplier'
    ]

    // MDL Drilling Headers
    mdlDrillingHeaders = [
      "BuildPriorityNumber",
      "MaterialType",
      "MaterialShortDesc",
      "MaterialId",
      "MarketUnitPrice",
      "Tier",
      "HoleSection",
      "HSType",
      "MGroup",
      "OD",
      "Wall",
      "Weight",
      "Grade",
      "Connection",
      "vendor",
      "manufacturerNum",
      "SourService",
      "ManufacturerName",
      "UoM",
      "VendorSAPNumber"
    ];

    // MDL Completions Headers
    mdlCompletionsHeaders = [
      "ComponentTypeId",
      "groupName",
      "MaterialGroup",
      "projectTags",
      "TradeName",
      "MaterialNumber",
      "VendorSAPNumber",
      "UoM",
      "SupplierPartNumber",
      "LegacyRefNumber",
      "NominalOd1",
      "NominalOd2",
      "NominalOd3",
      "ActualOd1",
      "ActualOd2",
      "ActualOd3",
      "ActualId1",
      "ActualId2",
      "ActualId3",
      "Weight1",
      "Weight2",
      "Weight3",
      "WallThickness",
      "MaterialGradeId1",
      "MaterialGradeId2",
      "MaterialGradeId3",
      "YeildStrength",
      "TopendConnectionId",
      "MiddleendConnectionId",
      "BottomendConnectionId",
      "ConnectionConfigId",
      "ConnectionType",
      "RangeId",
      "ElastomersMinTempRating",
      "ElastomersMaxTempRating",
      "MaxPressureRating",
      "AxialStrength",
      "MaxTempRating",
      "DiffPressureRating",
      "BurstPressure",
      "CollapsePressure",
      "QualityPlanDesignation",
      "ElastomerNotes",
      "StandardNotes",
      "AdministrativeNotes",
      "SupplierId",
      "MaterialDescription",
      "Drift",
      "ManufacturerId",
      "IsThreadedConnection",
      "IsContainsElastomerElements",
      "ConnectionBurstPressure",
      "ConnectionCollapsePressure",
      "ConnectionYeildStrength",
      "MakeupLoss",
      "RBW",
      "elastomerTypeID"
    ];

}