export enum DocumentEntityTypes {
  WELL = "WELL",
  MATERIAL = "MATERIAL",
  SPEC_SHEET = "MATERIAL_SPEC_SHEET",
  CVX_PO = "MATERIAL_CVX_PO",
  COMPLETION_MATERIAL="COMPLETION_MATERIA",
  YARD_INVENTORY ="YARD_INVENTORY",
  INSPECTION_REPORT ="INSPECTION_REPORT",
  CONTROL_LINE="CONTROL_LINE",
  RAW_DATA="RAW_DATA",
  RAW_DATA_COMPLETION="RAW_DATA_COMPLETION",
  TYR = "TYR",
}