export enum MasterObjectKeys {
  Lookup = "Lookup",
  GetFields = "GetFields",
  GetProjects = "GetProjects",
  GetFunctions = "GetFunctions",
  GetWells = "GetWells",
  GetAllWells = "GetAllWells",
  GetAllThorWells = "GetAllThorWells",
  GetOdinInventories = "GetOdinInventories",
  GetThorInventories = "GetThorInventories",
  GetWellDetails = "GetWellDetails",
  GetDocumentTypesByEntity = "GetDocumentTypesByEntity",
  SaveDocument = "SaveDocument",
  SaveCompletionDocument = "SaveCompletionDocument",
  GetDocuments = "GetDocuments",
  GetCompletionDocuments="GetCompletionDocuments",
  GetDocumentDetails = "GetDocumentDetails",
  GetDocumentMetadata = "GetDocumentMetadata",
  DeleteDocument = "DeleteDocument",
  GetMaterials = "GetMaterials",
  GetTYRExceptionDetails = "GetTYRExceptionDetails",
  GetTYRDocumentsByCase = "GetTYRDocumentsByCase",
  GetWellCoordinatorsList = 'GetWellCoordinatorsList',
  GetPlanningEnginnersList = 'GetPlanningEnginnersList',
}