export interface Inventory {
  id: number;
  rawdataId: number;
  materialID: string;
  category2Bucket: string;
  plantCode: string;
  partnerAuditClaimPlantCode: string;
  asset: string;
  onHandQuantity: number | null;
  valuationType: string;
  generalAccount: number | null;
  jackAndStMalo: number | null;
  tahiti: number | null;
  bigFoot: number | null;
  blindFaith: number | null;
  anchor: number | null;
  ballymore: number | null;
  surplus: number | null;
  inventoryItemID: string;
  oldInventoryItemID: string;
  sourceSystem: string;
  originalSourceSystem: string;
  businessUnitID: string;
  plantName: string;
  storageLocationDesc: string;
  storageLocationCode: string;
  storageBin: string;
  batch: string;
  wbsElementID: string;
  wbsElementDesc: string;
  category1Asset: string;
  serialNumber: string;
  oldMaterialNumber: string;
  materialType: string;
  materialShortDesc: string;
  materialLongDesc: string;
  manufacturingPartNumber: string;
  tier: string;
  od: number | null;
  wallThickness: number | null;
  weight: string;
  grade: string;
  connection: string;
  sourService: string;
  uoM: string;
  aUoM: string;
  materialCondition: string;
  enterpriseCategory: string;
  segment: string;
  family: string;
  class: string;
  mRPType: string;
  mRPArea: string;
  mRPTypeAtMRPArea: string;
  mRPTypeAtPlant: string;
  purchaseGroup: string;
  externalMaterialGroup: string;
  materialGroup: string;
  criticalCode: string;
  criticalFlag: string;
  critical: string;
  materialStatus: string;
  specialStockType: string;
  jointVenture: string;
  maxQuantity: number | null;
  minQuantity: number | null;
  blockQuantity: number | null;
  aUoMQuantity: number | null;
  totalQuantity: number | null;
  unitPriceLocal: number | null;
  unitPriceUSD: number | null;
  amountLocal: number | null;
  amountUSD: number | null;
  valuatedAmountUSD: number | null;
  valuatedAmountLocal: number | null;
  netBookValue: number | null;
  openPOQuantity: number | null;
  openPOValue: number | null;
  leadTime: number | null;
  forecastQuantity: number | null;
  nonMovingLastIssueDate: Date | null;
  ageingCalculationDate: Date | null;
  lastUsedDateByBU: Date | null;
  lastUsedDateByPlant: Date | null;
  lastMovementDateByPlant: Date | null;
  assemblyID: string;
  itemType: string;
  supplier: string;
  supplierPartNumber: string;
  vendor: string;
  expectedDate: Date | null;
  manufacturer: string;
  manufacturerDate: Date | null;
  size: string;
  length: number | null;
  documentNumber: string;
  documentLineNumber: string;
  commodityCode: string;
  commodityCodeDesc: string;
  demandFlag: string;
  moveQuantity: number | null;
  costCenterID: string;
  costCenterName: string;
  surplusFlag: string;
  hashDiff: string;
  deleted: boolean | null;
  createdTS: Date | null;
  lastUpdatedTS: Date | null;
  transferOpportunityFlag: string;
  derivedLastMovementDate: Date | null;
  ageTimeBucket: string;
  ageByMovementInMonths: number | null;
  materialAgeInMonths: number | null;
  lastUsedByBUInMonths: number | null;
  proposedStatus: string;
  proposedReason: string;
  investmentRecoveryStatus: string;
  orgFunction: string;
  ageTimeBucketSort: string;
  crateID: string;
  crateName: string;
  tagId: string;
  ageingDate: Date | null;
  lastUsedDate: Date | null;
  ageingMovementType: string;
  lastUsedMovementType: string;
  ageingTimeFrame: string;
  lastUsedTimeFrame: string;
  lastMovementTimeFrame: string;
  valuationClass: string;
  mMRLevel1Category: string;
  mMRLevel2Category: string;
  mMRLevel3Category: string;
  chevronMMR: string;
  connectionConfiguration: string;
  qualityPlan: string;
  readyForServiceDate: string;
  dateCreated: Date | null;
  userIdCreatedBy: number | null;
  dateLastModified: Date | null;
  userIdModifiedBy: number | null;
  isDeleted: number | null;
}



