export class masterdatalibraryModel {
  cvxCrwId?: number;
  materialNumber?: string;
  isSupplierSpecificFlag: number;
  componentTypeID?: number;
  materialGradeId1?: number;
  materialGradeId2?: number;
  materialGradeId3?: number;
  rangeId?: number;
  topendConnectionId?: number;
  middleendConnectionId?: number;
  bottomendConnectionId?: number;
  connectionConfigId?: number;
  materialDescription?: string;
  tradeName?: string;
  supplierPartNumber?: string;
  legacyRefNumber?: string;
  nominalOd1?: number;
  nominalOd2?: number;
  nominalOd3?: number;
  wallThickness?: number;
  yeildStrength?: number;
  drift?: number;
  weight1?: number;
  weight2?: number;
  weight3?: number;
  actualOd1?: number;
  actualOd2?: number;
  actualOd3?: number;
  maxTempRating?: number;
  actualId1?: number;
  actualId2?: number;
  actualId3?: number;
  qualityPlanDesignation?: string;
  elastomersMinTempRating?: number;
  elastomersMaxTempRating?: number;
  elastomerNotes?: string;
  standardNotes?: string;
  maxPressureRating?: number;
  diffPressureRating?: number;
  burstPressure?: number;
  collapsePressure?: number;

  isThreadedConnection?: number;
  isContainsElastomerElements?: number;
  connectionBurstPressure?: number;
  connectionCollapsePressure?: number;
  connectionYeildStrength?: number;
  makeupLoss?: number;
  elastomerTypeID?: number;

  organizationId?: number;
  organizationName?: string;
  componentTypeName?: string;
  materialGradePrimary?: string;
  materialGradeSecondary?: string;
  materialGradeTertiary?: string;
  rangeName?: string;
  topConnection?: string;
  middleConnection?: string;
  bottomConnection?: string;
  connectionConfigName?: string;
  connectionConfigType?: string;
  manufacturerDetails?: string;
  manufacturerId?: number;
  groupId?: number;
  groupName?: string;
  sectionId ?:number
  sectionName ?:string;
  projectTags?:string
  administrativeNotes?:string;
  editable?: boolean;
  connectionTypeId?: number;
  connectionTypeName?: string;
  axialStrength?: number;
  materialGroup?: string;
  rbwId?: number; // Added RBW field
  rbw?: number;

  constructor(init?: Partial<masterdatalibraryModel>) {
    // Destructure init for easier assignment
    this.cvxCrwId = init?.cvxCrwId ?? 0;
    this.materialNumber = init?.materialNumber || '';
    this.isSupplierSpecificFlag = init?.isSupplierSpecificFlag ?? 0;  // Using nullish coalescing
    this.componentTypeID = init?.componentTypeID ?? 0;
    this.materialGradeId1 = init?.materialGradeId1 ?? 0;
    this.materialGradeId2 = init?.materialGradeId2 ?? 0;
    this.materialGradeId3 = init?.materialGradeId3 ?? 0;
    this.rangeId = init?.rangeId ?? 0;
    this.topendConnectionId = init?.topendConnectionId ?? 0;
    this.middleendConnectionId = init?.middleendConnectionId ?? 0;
    this.bottomendConnectionId = init?.bottomendConnectionId ?? 0;
    this.connectionConfigId = init?.connectionConfigId ?? 0;
    this.materialDescription = init?.materialDescription || '';
    this.tradeName = init?.tradeName || '';
    this.supplierPartNumber = init?.supplierPartNumber || '';
    this.legacyRefNumber = init?.legacyRefNumber || '';
    this.nominalOd1 = init?.nominalOd1 ?? 0;
    this.nominalOd2 = init?.nominalOd2 ?? 0;
    this.nominalOd3 = init?.nominalOd3 ?? 0;
    this.wallThickness = init?.wallThickness ?? 0;
    this.yeildStrength = init?.yeildStrength ?? 0;
    this.drift = init?.drift ?? 0;
    this.weight1 = init?.weight1 ?? 0;
    this.weight2 = init?.weight2 ?? 0;
    this.weight3 = init?.weight3 ?? 0;
    this.actualOd1 = init?.actualOd1 ?? 0;
    this.actualOd2 = init?.actualOd2 ?? 0;
    this.actualOd3 = init?.actualOd3 ?? 0;
    this.maxTempRating = init?.maxTempRating ?? 0;
    this.actualId1 = init?.actualId1 ?? 0;
    this.actualId2 = init?.actualId2 ?? 0;
    this.actualId3 = init?.actualId3 ?? 0;
    this.qualityPlanDesignation = init?.qualityPlanDesignation || '';
    this.elastomersMinTempRating = init?.elastomersMinTempRating ?? 0;
    this.elastomersMaxTempRating = init?.elastomersMaxTempRating ?? 0;
    this.elastomerNotes = init?.elastomerNotes || '';
    this.standardNotes = init?.standardNotes || '';
    this.maxPressureRating = init?.maxPressureRating ?? 0;
    this.diffPressureRating = init?.diffPressureRating ?? 0;
    this.burstPressure = init?.burstPressure ?? 0;
    this.collapsePressure = init?.collapsePressure ?? 0;

    this.isThreadedConnection = init?.isThreadedConnection ?? 0;
    this.isContainsElastomerElements = init?.isContainsElastomerElements ?? 0;
    this.connectionBurstPressure = init?.connectionBurstPressure ?? 0;
    this.connectionCollapsePressure = init?.connectionCollapsePressure ?? 0;
    this.connectionYeildStrength = init?.connectionYeildStrength ?? 0;
    this.makeupLoss = init?.makeupLoss ?? 0;
    this.elastomerTypeID = init?.elastomerTypeID ?? 0;

    this.organizationId = init?.organizationId ?? 0;
    this.organizationName = init?.organizationName || '';
    this.componentTypeName = init?.componentTypeName || '';
    this.materialGradePrimary = init?.materialGradePrimary || '';
    this.materialGradeSecondary = init?.materialGradeSecondary || '';
    this.materialGradeTertiary = init?.materialGradeTertiary || '';
    this.rangeName = init?.rangeName || '';
    this.topConnection = init?.topConnection || '';
    this.middleConnection = init?.middleConnection || '';
    this.bottomConnection = init?.bottomConnection || '';
    this.connectionConfigName = init?.connectionConfigName || '';
    this.connectionConfigType = init?.connectionConfigType || '';
    this.manufacturerDetails = init?.manufacturerDetails || '';
    this.manufacturerId = init?.manufacturerId ?? 0;
    this.groupId = init?.groupId ?? 0;
    this.groupName = init?.groupName || '';
    this.sectionId = init?.sectionId ?? 0;
    this.sectionName = init?.sectionName || '';
    this.projectTags = init?.projectTags || '';
    this.administrativeNotes = init?.administrativeNotes || '';
    this.connectionTypeId = init?.connectionTypeId ?? 0;
    this.connectionTypeName = init?.connectionTypeName || '';
    this.axialStrength = init?.axialStrength ?? 0;
    this.materialGroup = init?.materialGroup || '';
    this.rbwId = init?.rbwId ?? 0;
    this.rbw = init?.rbw ?? 0;
  }
};
