export class masterdatalibraryModelTable {
  cvxCrwId?: number;
  materialNumber?: string;
  isSupplierSpecificFlag: number;
  componentTypeID?: number;
  materialGradeId1?: number;
  materialGradeId2?: number;
  materialGradeId3?: number;
  rangeId?: number;
  topendConnectionId?: number;
  middleendConnectionId?: number;
  bottomendConnectionId?: number;
  connectionConfigId?: number;
  materialDescription?: string;
  materialGroup?: string;  // Add material group property
  rbwId?: number; // Added RBW field
  tradeName?: string;
  supplierPartNumber?: string;
  legacyRefNumber?: string;
  nominalOd1?: number;
  nominalOd2?: number;
  nominalOd3?: number;
  wallThickness?: number;
  yeildStrength?: number;
  drift?: number;
  weight1?: number;
  weight2?: number;
  weight3?: number;
  actualOd1?: number;
  actualOd2?: number;
  actualOd3?: number;
  maxTempRating?: number;
  actualId1?: number;
  actualId2?: number;
  actualId3?: number;
  qualityPlanDesignation?: string;
  elastomersMinTempRating?: number;
  elastomersMaxTempRating?: number;
  elastomerNotes?: string;
  standardNotes?: string;
  maxPressureRating?: number;
  axialStrength?:number;
  diffPressureRating?: number;
  burstPressure?: number;
  collapsePressure?: number;
  isThreadedConnection?: number;
  isContainsElastomerElements?: number;
  connectionBurstPressure?: number;
  connectionCollapsePressure?: number;
  connectionYeildStrength?: number;
  makeupLoss?: number;
  elastomerTypeID?: number;
  manufacturerId?: number;
  userIdCreatedBy?: string;
  dateCreated?: Date;
  dateLastModified?: Date;
  userIdModifiedBy?: string;
  isDeleted?: number;
  supplierId?: number;
  groupId?: number;
  groupName?: string;
  sectionId ?:number
  projectTags?:string
  administrativeNotes?: string;
  leadTimeInDays?: number;
  requiredBackup?: number;
  odinActions?: string;
  OdinActionLookupId?: number;
  odinComments?: string;
  connectionTypeId?: number;
  documentCount ?:number;
  uoMid?: number;
  uom?: string;
  vendorSapnumber?: string;
  overrideInventory?: number;

  constructor(init?: Partial<masterdatalibraryModelTable>) {
    // Destructure init for easier assignment
    this.cvxCrwId = init?.cvxCrwId ?? 0;
    this.materialNumber = init?.materialNumber || '';
    this.isSupplierSpecificFlag = init?.isSupplierSpecificFlag ?? 0;  // Using nullish coalescing
    this.componentTypeID = init?.componentTypeID ?? 0;
    this.materialGradeId1 = init?.materialGradeId1 ||null;
    this.materialGradeId2 = init?.materialGradeId2 ||null;
    this.materialGradeId3 = init?.materialGradeId3 ||null;
    this.rangeId = init?.rangeId ||null;
    this.topendConnectionId = init?.topendConnectionId ||null;
    this.middleendConnectionId = init?.middleendConnectionId ||null;
    this.bottomendConnectionId = init?.bottomendConnectionId ||null;;
    this.connectionConfigId = init?.connectionConfigId ||null;
    this.materialDescription = init?.materialDescription || '';
    this.materialGroup = init?.materialGroup || '';
    this.rbwId = init?.rbwId ||null; // Added RBW initialization
    this.tradeName = init?.tradeName || '';
    this.supplierPartNumber = init?.supplierPartNumber || '';
    this.legacyRefNumber = init?.legacyRefNumber || '';
    this.nominalOd1 = init?.nominalOd1 ?? 0;
    this.nominalOd2 = init?.nominalOd2 ?? 0;
    this.nominalOd3 = init?.nominalOd3 ?? 0;
    this.wallThickness = init?.wallThickness ?? 0;
    this.yeildStrength = init?.yeildStrength ?? 0;
    this.drift = init?.drift ?? 0;
    this.weight1 = init?.weight1 ?? 0;
    this.weight2 = init?.weight2 ?? 0;
    this.weight3 = init?.weight3 ?? 0;
    this.actualOd1 = init?.actualOd1 ?? 0;
    this.actualOd2 = init?.actualOd2 ?? 0;
    this.actualOd3 = init?.actualOd3 ?? 0;
    this.maxTempRating = init?.maxTempRating ?? 0;
    this.actualId1 = init?.actualId1 ?? 0;
    this.actualId2 = init?.actualId2 ?? 0;
    this.actualId3 = init?.actualId3 ?? 0;
    this.qualityPlanDesignation = init?.qualityPlanDesignation || '';
    this.elastomersMinTempRating = init?.elastomersMinTempRating ?? 0;
    this.elastomersMaxTempRating = init?.elastomersMaxTempRating ?? 0;
    this.elastomerNotes = init?.elastomerNotes || '';
    this.standardNotes = init?.standardNotes || '';
    this.maxPressureRating = init?.maxPressureRating ?? 0;
    this.diffPressureRating = init?.diffPressureRating ?? 0;
    this.burstPressure = init?.burstPressure ?? 0;
    this.collapsePressure = init?.collapsePressure ?? 0;

    this.isThreadedConnection = init?.isThreadedConnection ?? 0;
    this.isContainsElastomerElements = init?.isContainsElastomerElements ?? 0;
    this.connectionBurstPressure = init?.connectionBurstPressure ?? 0;
    this.connectionCollapsePressure = init?.connectionCollapsePressure ?? 0;
    this.connectionYeildStrength = init?.connectionYeildStrength ?? 0;
    this.makeupLoss = init?.makeupLoss ?? 0;
    this.elastomerTypeID = init?.elastomerTypeID ?? 0;
    this.manufacturerId = init?.manufacturerId ?? 0;
    this.userIdCreatedBy = init?.userIdCreatedBy || '';
    this.dateCreated = init?.dateCreated || undefined;
    this.dateLastModified = init?.dateLastModified || new Date();
    this.userIdModifiedBy = init?.userIdModifiedBy || '';
    this.isDeleted = init?.isDeleted ?? 0;
    this.supplierId = init?.supplierId ?? 0;
    this.groupId = init?.groupId ||null;
    this.groupName = init?.groupName || '';
    this.sectionId = init?.sectionId ?? 0;
    this.projectTags = init?.projectTags || '';
    this.administrativeNotes = init?.administrativeNotes || '';
    this.leadTimeInDays = init?.leadTimeInDays ?? 0;
    this.requiredBackup = init?.requiredBackup ?? 0;
    this.odinActions = init?.odinActions || '';
    this.odinComments = init?.odinComments || '';
    this.OdinActionLookupId = init?.OdinActionLookupId ?? null;
    this.connectionTypeId = init?.connectionTypeId ||null;
    this.axialStrength = init?.axialStrength ?? 0;
    this.documentCount=init?.documentCount??0;
    this.uoMid = init?.uoMid ?? 0;
    this.uom = init?.uom || '';
    this.vendorSapnumber = init?.vendorSapnumber || '';
    this.overrideInventory = init?.overrideInventory ?? 0; // Initialize overrideInventory
  }
};
