export interface MaterialSaveModel{
          holeSection: string,
          hsType: string,
          mGroup:string,
          materialType: string,
          marketUnitPrice:number,
          materialShortDesc:string,
          tier:string,
          materialId: number,
          od:number,
          weight:number,
          wall:number,
          grade:string,
          connection:string,
          vendor:string,
          sourservice:string,
          manufacturerNum:number,
          sooner:number,
          tenaris:number,
          drillQuip:number,
          openOrClosed:string,
          leadTimeInDays:Number,
}